name: ESLint

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install modules
        run: npm install
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build modules
        run: npm run build
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run ESLint
        run: ./node_modules/.bin/eslint . --ext .js
